version: '3'
services:
  engineering-week-challenge:
    build:
      context: .
      dockerfile: Dockerfile
    image: istarlabs/engineering-week-challenge
    restart: unless-stopped
    volumes:
      - leaderboard:/app
    ports:
      - "5000:5000"
    container_name: engineering-week-challenge
    environment:
      - PASSWORD=${PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

volumes:
  leaderboard: